version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python ./evs_bids/manage.py migrate --noinput
    command: python ./evs_bids/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/thesis
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db

volumes:
  postgres_data: