version: '3.6'

services:
  db:
    image: postgres:9.6
  web:
    build: .
    image: thesis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./thesis:/opt/thesis
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=secret
      - DJANGO_SETTINGS_MODULE=evs_bids.settings
