# Generated by Django 2.1.3 on 2019-04-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetching_bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField(unique=True)),
                ('receive_date', models.DateTimeField()),
                ('energy_coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hour_coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_loss', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BidDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetching_bids.Bid')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids_decisions.AggregatorDecision')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingLocalizationDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bid_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_localization_decisions', to='bids_decisions.BidDecision')),
                ('charging_localization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetching_bids.ChargingLocalization')),
            ],
        ),
    ]
