# Generated by Django 2.1.3 on 2019-04-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids_decisions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatordecision',
            name='decision',
        ),
        migrations.AddField(
            model_name='charginglocalizationdecision',
            name='decision',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aggregatordecision',
            name='decision_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='charginglocalizationdecision',
            name='bid_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_localization_decisions', to='bids_decisions.BidDecision'),
        ),
    ]
