# Generated by Django 2.1.3 on 2019-05-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('global', 'global'), ('by_localization', 'by_loc')], max_length=6)),
                ('decision_date', models.DateField(unique=True)),
                ('receive_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorGroupDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('energy_coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hour_coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_group_decisions', to='decisions.AggregatorDecision')),
            ],
        ),
        migrations.CreateModel(
            name='DateRangeDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyHourOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_index', models.IntegerField()),
                ('energy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_schemas', models.IntegerField()),
                ('total_energy', models.IntegerField()),
                ('group_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='decisions.AggregatorGroupDecision')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_decisions', to='decisions.AggregatorGroupDecision')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='energyhouroffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_offers', to='decisions.Offer'),
        ),
        migrations.AddField(
            model_name='daterangedecision',
            name='schedule_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_decision_date_ranges', to='decisions.ScheduleDecision'),
        ),
    ]
